spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentalhub
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true

server:
  port: 8080
